server:
    post: 8080

swagger2:
    enable: true

spring:
    profiles:
        active: prod
    feign:
        hystrix:
            enabled: true
        client:
            config:
                default:
                connectTimeout: 5000
                readTimeout: 5000
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8

#     mvc:
#         static-path-pattern: /**

mybatis:
    typeAliasesPackage: cool.cxc.app.*.model
    mapperLocations: classpath:mybatis/mapper/*.xml

tencent:
    SecretId: AKIDEG2Xlna6KIyOXQ2NQCixvb1A2cwzlGTQ
    SecretKey: h7G8k47tOcZFemdCVXTHrBF4kAKEsITQ
    SDKAppID: 1400639127
    TemplateId: 1317611
    SignName: 单色不单调de


